export const locationToCountryCode: { [key: string]: string } = {
  "Sakhir": "bh",
  "Jeddah": "sa",
  "Melbourne": "au",
  "Imola": "it",
  "Monte Carlo": "mc",
  "Barcelona": "es",
  "Spielberg": "at",
  "Silverstone": "gb",
  "Budapest": "hu",
  "Spa-Francorchamps": "be",
  "Monza": "it",
  "Baku": "az",
  "Lusail": "qa",
  "Yas Island": "ae",
  "Le Castellet": "fr",
  "Sochi": "ru",
  "Jerez de la Frontera": "es",
  "Zandvoort": "nl",
  "Mugello": "it"
};